ren "C:\Work\GitHub\m3u-gen\test\Lenny Kravitz - The Very Best (1996)\01_Lenny_Kravitz_-_Are_You_Gonna_Go_My_Way.mp3" "01 Lenny Kravitz - Are You Gonna Go My Way.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Lenny Kravitz - The Very Best (1996)\02_Lenny_Kravitz_-_Rock_'n'_Roll_Is_Dead.mp3" "02 Lenny Kravitz - Rock 'n' Roll Is Dead.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Lenny Kravitz - The Very Best (1996)\03_Lenny_Kravitz_-_Always_on_the_Run.mp3" "03 Lenny Kravitz - Always on the Run.mp3"
del "C:\Work\GitHub\m3u-gen\test\Lenny Kravitz - The Very Best (1996)\Lenny Kravitz - The Very Best (1996).m3u"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Alya_-_Brazil.mp3" "Alya - Brazil.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Fergie_-_Big_Girls_Don't_Cry_(Personal).mp3" "Fergie - Big Girls Don't Cry (Personal).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\I'LL_STAND_BY_YOU_(Lyrics)_-_THE_PRETENDERS.mp3" "I'LL STAND BY YOU (Lyrics) - THE PRETENDERS.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Imagine_Dragons_-_Demons_(Official).mp3" "Imagine Dragons - Demons (Official).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Joss_Stone_-_Right_to_be_Wrong.mp3" "Joss Stone - Right to be Wrong.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Justin_Timberlake_-_Cry_Me_A_River_(Official).mp3" "Justin Timberlake - Cry Me A River (Official).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\LETEČI_POTEPUHI-Bicikl_(video).mp3" "LETEČI POTEPUHI-Bicikl (video).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Pearl_Jam_-_Army_Reserve_(Pearl_Jam).mp3" "Pearl Jam - Army Reserve (Pearl Jam).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Pearl_Jam-Last_Kiss.mp3" "Pearl Jam-Last Kiss.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Sugababes_-_Breathe_Easy.mp3" "Sugababes - Breathe Easy.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Morcheeba_-_Enjoy_The_Ride_(Feat._Judy_Tzuke).mp3" "Morcheeba - Enjoy The Ride (Feat. Judy Tzuke).mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\09_Crowded_House_-_Don't_Dream_It's_Over.mp3" "09 Crowded House - Don't Dream It's Over.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Misc\09._Holding_On_To_You.mp3" "09. Holding On To You.mp3"
del "C:\Work\GitHub\m3u-gen\test\Misc\Misc.m3u"
ren "C:\Work\GitHub\m3u-gen\test\Misc\Misc.m3u-2017-05-23-16-45-15.bak" "Misc.m3u"
ren "C:\Work\GitHub\m3u-gen\test\Radiohead - The Best Of [2008]\1-02_Paranoid_Android.mp3" "1-02 Paranoid Android.mp3"
ren "C:\Work\GitHub\m3u-gen\test\Radiohead - The Best Of [2008]\1-03_Karma_Police.mp3" "1-03 Karma Police.mp3"
del "C:\Work\GitHub\m3u-gen\test\Radiohead - The Best Of [2008]\Radiohead - The Best Of [2008].m3u"
ren "C:\Work\GitHub\m3u-gen\test\The Best Of Blur (sidthefish)\02-Song_2.mp3" "02-Song 2.mp3"
ren "C:\Work\GitHub\m3u-gen\test\The Best Of Blur (sidthefish)\03-There's_No_Other_Way.mp3" "03-There's No Other Way.mp3"
del "C:\Work\GitHub\m3u-gen\test\The Best Of Blur (sidthefish)\The Best Of Blur (sidthefish).m3u"
del C:\Work\GitHub\m3u-gen\test\undo-2017-05-23-16-45-15.cmd

pause
